### PR TITLE
Updated .deb packages for the 0.3 release

### PR DESCRIPTION
**Pull request by osamasal**
Still yet to be tested to ensure that the C++ samples build and run as expected.

### CODE REVIEW

**Comment by anown0** [comment]
The host-side release-0.3 packages built by CI are located here:

```
/mnt/zen-ffa/ci/release/release-0.3.tar.gz
```
The target (i.e. ZPU) release-0.3 package built by CI is here:
```
Release-armv8-ff15b5cf6d7ad58a51adcae76c7cd700b7609f90-1742-install.tar.gz
```

Each of those should have the required `.deb` packages to be used for testing.

**Comment by osamasal** [comment]
@anown0 this PR needs to be updated with the new `.deb` files.

**Comment by osamasal** [comment]
@anown0 I think we still need to update the .deb packages in this PR, right?

**Comment by daydreamer2023** [comment]
I had a try, but still got `Truncated data`.
The script I used is the same as #37 .
@osamasal

**Comment by osamasal** [comment]
@anown0 does this PR have the latest packages that need to be shipped in the `0.3` release?

**Comment by anown0** [comment]
I've updated the .deb packages to match release-0.3.

**Pull request merged**
