### PR TITLE
Python proto

### PR DESCRIPTION
**Pull request by ghsyu**
Changes the install location of the protobufs and compiled files, and adds the command to generate the python compiled .proto files along with the C++ ones. Since this directory now contains live code, don't delete it during `make clean`

### CODE REVIEW

**Review by osamasal — APPROVED** [review]

**Comment by osamasal** [comment]
@ghsyu please hold off on merging this PR until I've created a git tag for the current ```main```

This is now done. Feel free to merge your PR.

**Review by plb9772 — CHANGES_REQUESTED** [review]
I think to make it complete, we should:
- remove the script `make_data_proto.sh` which is useless now
- update the `environment.sh` to point to the directory where the python protobufs will be installed (`usr/lib/zendar`)
- update the setup instruction accordingly.

Furthermore, if I understand correctly, there will be no data_pb2.py in the protobufs installed by the packages from ZenCode but its different sub-proto parts. If this is true, we will need to change the import statements in the python scripts.

Finally, we want to update ZenBook Setup instructions correctly, especially the PythonPath. We would need to remove `${PYTHONPATH}:${ZEN_SDK}/protocol` and when the protobuf compilation will be consolidated under `build/protocol` we need to make sure that this is these protobufs that will be used in python. For internal development reason, this means that the `environment.sh` should append the path to the installed protobufs at the end of the python path and not at the beginning. I think it won't change anything for the customer, but it makes sure that we will be using the ones from ZenCode when developping (even if someone source `environment.sh`).

**Comment by ghsyu** [comment]
> I think to make it complete, we should:
> 
> * remove the script `make_data_proto.sh` which is useless now
> * update the `environment.sh` to point to the directory where the python protobufs will be installed (`usr/lib/zendar`)
> * update the setup instruction accordingly.
> 
> Furthermore, if I understand correctly, there will be no data_pb2.py in the protobufs installed by the packages from ZenCode but its different sub-proto parts. If this is true, we will need to change the import statements in the python scripts.
> 
> Finally, we want to update ZenBook Setup instructions correctly, especially the PythonPath. We would need to remove `${PYTHONPATH}:${ZEN_SDK}/protocol` and when the protobuf compilation will be consolidated under `build/protocol` we need to make sure that this is these protobufs that will be used in python. For internal development reason, this means that the `environment.sh` should append the path to the installed protobufs at the end of the python path and not at the beginning. I think it won't change anything for the customer, but it makes sure that we will be using the ones from ZenCode when developping (even if someone source `environment.sh`).

This all seems good, except that there will still be a data_pb2.py in the protobufs installed by ZenCode. However, there may still need to be changes to the python side, since the protobufs' package names will change.

**Comment by plb9772** [comment]
@ghsyu why is there still a data.proto ? I thought it is just the concatenation of other protobufs. I think that keeping it makes us loose the advantage of refactoring the protobufs of ZenCode and ZendarSDK, since there would still be some code duplication. For example, if we change `tracker.proto`, we will need to port the changes to `data.proto`.
Yes, you are right, the package names will need to be changed on the python side

**Comment by ghsyu** [comment]
There is an original `data.proto` that the `data.proto` in `ZendarSDK` is a copy of. It should contain everything we care about, the version in `ZendarSDK` just concatenates all of its dependencies into the same file.

**Review by plb9772 — APPROVED** [review]
All these changes looks good to me. It seems to me that the PR can be merged as it is now and still works for both customers and developers. Thank you very much.

**Pull request merged**
