### PR TITLE
Render lidar

### PR DESCRIPTION
**Pull request by ghsyu**
Adds lidar support to `image_viewer.py`. Usage is consistent with the existing sar and tracker flags, so `-no-lidar` disables the lidar display. The lidar code expects a file named `lidar.pbs` in the `--input-dir` directory.

### CODE REVIEW

**Comment by mostajabi** [comment]
It worked well with lidar and SAR, but it failed with --no-sar option:
`python3 image_viewer.py  -i /mnt/zen-ffa/nyquist/2021-01-13_0000/002/analysis/  --radar-name ZRAA0019 -o ~/tmp/ --no-sar`

**Comment by mostajabi** [comment]
I think it is better to have no lidar overlay output as default and have the lidar overlay if we set the flag. Because we may not have lidar for some of our datasets and it should be processed even if we have collected lidar data. Let me know what you think.

**Comment by ghsyu** [comment]
> It worked well with lidar and SAR, but it failed with --no-sar option:
> `python3 image_viewer.py -i /mnt/zen-ffa/nyquist/2021-01-13_0000/002/analysis/ --radar-name ZRAA0019 -o ~/tmp/ --no-sar`

Looking into this

> I think it is better to have no lidar overlay output as default and have the lidar overlay if we set the flag. Because we may not have lidar for some of our datasets and it should be processed even if we have collected lidar data. Let me know what you think.

Makes sense.

**Comment by ghsyu** [comment]
Looks like there's an error with the existing code's handling of local coordinates, which I will try to fix.

**Comment by mostajabi** [comment]
Thanks Gilbert. Lidar points look good now. 

@jimmy-zendar  when we use --no-sar flag, lidar local points look similar to ECEF point projection of lidar point cloud to a dummy black image. However tracking points with --no-sar flag don't align with cartesian lidar points and have vehicle centric view. You can test it with

`python3 image_viewer.py  -i /mnt/zen-ffa/nyquist/2021-01-13_0000/001/analysis/  --radar-name ZRAA0019 -o ~/tmp/  --lidar --no-sar`

`python3 image_viewer.py  -i /mnt/zen-ffa/nyquist/2021-01-13_0000/001/analysis/  --radar-name ZRAA0019 -o ~/tmp/ --lidar`

Let us know your opinion on this.

**Comment by jimmy-zendar** [comment]
So in the example Reza gave, it seems like the lidar point cloud and radar point cloud are not lining up right?

**Review by mostajabi — APPROVED** [review]
Lidar and radar overlay works fine for global coordinates with SAR. Let's push the changes and then create a ticket for local misalignment between lidar and radar.

**Pull request merged**
