### PR TITLE
Parallelize radar visualization in image_viewer

### PR DESCRIPTION
**Pull request by plb9772**
When using `image_viewer`, I find a bit annoying that we see only one radar at a time, and the fact that they are successively generated makes the process of obtaining merged video quite long. This is a proposal to make every radar processed in parallel (but not in sync), without changing too much the current logic.

I tested it, and the gain of time is consequent. Let me know what you think of it

### CODE REVIEW

**Review by jimmy-zendar — COMMENTED** [review]
When I run the code, I ran into
`Gdk-Message: 15:14:14.198: image_viewer.py: Fatal IO error 0 (Success) on X server :1.

(image_viewer.py:14266): Gdk-ERROR **: 15:14:14.213: The program 'image_viewer.py' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadDrawable (invalid Pixmap or Window parameter)'.
  (Details: serial 480 error_code 9 request_code 139 (RENDER) minor_code 4)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
`

This error is related to creating the figure in line 146 in image_viewer.py. Maybe Reza can see if he can get that to work on his machine.

**Comment by mostajabi** [comment]
@jimmy-zendar I could run it fine.

**Comment by jimmy-zendar** [comment]
it works for me after the matplotlib backend change.

**Comment by mostajabi** [comment]
I like this feature. I think it would be significantly better if we can somehow synchronize the threads and visualize them in the same plot. But it needs more work to be done. This way we would also address our synchronizing issue #9. @jimmy-zendar what is your opinion on this?

**Comment by mostajabi** [comment]
With that being said, I think running the threads in parallel in its current format, saves time which is pretty good.

**Comment by plb9772** [comment]
For the synchronization of all the threads, we have to wait that Gilbert work with a separate output of the image model. I merged this PR now as it makes the workflow faster.

**Pull request merged**
