### PR TITLE
Improved DOA metrics update in protobuf

### PR DESCRIPTION
**Pull request by plb9772**
To follow the update in ZenCode, we define new outputs:
- `magnitude`: it was before the amplitude measured in the RD which was not very useful since it is not a per-object measurement and is redundant with the `rd_mean_snr`. It is now the magnitude of the coefficient of an object estimated by the DOA MLE estimator
- `doa_snr`: SNR measured after the DOA estimation. We estimate the variance of the noise as `sigma^2 = ||z - coeff * a(theta, phi)||^2 / (n - m)` where `n` is the number of measurements and `m` the number of parameters to estimate. We then have `doa_snr = |coeff| / sigma`
- `azimuth_variance`: is the variance on the estimate. It is defined as ` cov(theta) = sigma^2 * (Hessian(cost(theta))) ^ -1`
- `rd_mean_snr` replaces `confidence`

To be merged when the PR is approved in ZenCode

### CODE REVIEW

**Review by griffinfoster — APPROVED** [review]
Looks good.

**Comment by plb9772** [comment]
The PR in ZenCode is merged. I realized that since `amplitude` was renamed to `magnitude`, it can create a forward compatibility issue. @jimmy-zendar what do you think should be the way to move forward with that ?

**Comment by plb9772** [comment]
The path forward is to wait that `feature-algorithms` is merged into `master` and the debian packages are updated.

**Review by osamasal — APPROVED** [review]
Looks good.

**Pull request merged**
